spring:
  data:
    jdbc:
      dialect: postgresql

logging:
  level:
    root: INFO
    # org.springframework.boot.autoconfigure: DEBUG
    # org.mybatis.spring: DEBUG
    # com.zaxxer.hikari: DEBUG
    # org.springframework.beans.factory: DEBUG
    # com.everrefine.elms: DEBUG

upload:
  directory: uploads # ファイルアップロード先ディレクトリ

lesson:
  order:
    interval: 1024
    scale: 10
    reorder-threshold: 0.0000000001