spring:
  profiles:
    active: default

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.everrefine.elms.infrastructure.typehandler
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: DEBUG
    org.mybatis.spring: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.beans.factory: DEBUG
    com.everrefine.elms: DEBUG

upload:
  directory: uploads # ファイルアップロード先ディレクトリ